<div class="menu">
    <ul><?
        foreach ($this->menuItems as $menuItem) :
            if ($this->HasAccess($this->currentUser, $menuItem)) :
                if (isset($menuItem['subItems'])) :
                    echo $this->partial('menu/sub-items.phtml', array(
                        'subItems' => $menuItem['subItems'],
                        'menuItem' => $menuItem,
                        'currentMenu' => $this->currentMenu
                    ));
                else :
                    echo $this->partial('menu/item.phtml', array(
                        'menuItem' => $menuItem,
                        'currentMenu' => $this->currentMenu
                    ));
                endif;
            endif;
        endforeach;
    ?></ul>
</div>