<li>
    <a class="submenu-link" href="javascript:void(0);"><?
        echo $this->menuItem['name'];
        if (isset($this->menuItem['count']) && $this->menuItem['count'] > 0):
            echo ' (' . $this->menuItem['count'] . ') ';
        endif;
    ?></a>
    <ul class="submenu"><?
        foreach ($this->subItems as $subItem) :
            if ($this->hasAccess($this->currentUser, $subItem)) :
                echo $this->partial('menu/item.phtml', array(
                    'menuItem' => $subItem,
                    'currentMenu' => $this->currentMenu
                ));
            endif;
        endforeach;
    ?></ul>
</li>
